### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by laylatov** [Teaching-projects/SZE-FordProg-2020-BoolAlgebra-2#1]
Atnezesre szanva, hamarosan lesz Readme.md is

**Comment by laylatov** [comment]
Közben kész lett a Readme.md is.

**Comment by hegyhati** [comment]
Rendben van a dolog, hanyas jegyet szeretnel megcelozni?

**Comment by laylatov** [comment]
Ebből kihozható egy 4-5ös? Igazából a 4-es lenne gondolom a reálisabb.
Időmenedzselési szempontból nézve, a 4-est már szívesen el is fogadnám,
ha ezt reálisnak látod :)

**Comment by hegyhati** [comment]
Hat 5-oshoz tul egyszeru ez az egesz, a 4-es rendben van, mert szepen, magyarazva leirtad, meg van ez a valtozosdi dolog is.

**Comment by laylatov** [comment]
Köszönöm, a 4-es tökéletes lesz :)
